services:
  db:
    image: postgres:18
    container_name: lug-postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_DB: lug_dev
      POSTGRES_USER: lug_user
      POSTGRES_PASSWORD: lug_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://lug_user:lug_password@db:5432/lug_dev"
    ports:
      - "3000:3000"
    volumes:
      - blog_uploads:/data/uploads
    depends_on:
      - db

volumes:
  postgres_data:
  blog_uploads:
